@HOST=http://127.0.0.1
@PORT=:8080
@baseURL = {{HOST}}{{PORT}}

### Get account by id
GET {{baseURL}}/accounts/10 HTTP/1.1
Accept: application/json

### Create new account
POST {{HOST}}{{PORT}}/accounts
Content-Type: application/json

{
    "Owner": "Anna",
    "Currency": "USR"
}

### Get accounts
GET {{baseURL}}/accounts/?page_id=2&page_size=10
Accept: application/json

### Get account by id
DELETE {{baseURL}}/accounts/11
Accept: application/json