@HOST=http://127.0.0.1
@PORT=:8080
@baseURL = {{HOST}}{{PORT}}

### Get account by id
GET {{baseURL}}/accounts/1 HTTP/1.1
Accept: application/json

### Create new account
POST {{baseURL}}/accounts
Content-Type: application/json

{
    "Owner": "AnnaNTSNDD",
    "Currency": "USR"
}

### Get accounts
GET {{baseURL}}/accounts/?page_id=2&page_size=10
Accept: application/json

### Update account by id
PUT {{baseURL}}/accounts
Content-Type: application/json

{
    "ID": 1,
    "Balance": 50
}

### Delete account by id
DELETE {{baseURL}}/accounts/11
Accept: application/json

### Create new user
POST {{baseURL}}/users
Content-Type: application/json

{
    "username": "AnnaNTSNDD",
    "password": "hellohi",
    "full_name": "Anna Ivanova",
    "email": "annansatuhsatuhsa@mail.com"
}