set dotenv-load


# Start postgres db service
pg_start:
    docker compose start

# Stop postgres db service
pg_stop:
    docker compose stop

# Create bankdb
createdb:
    docker compose exec db createdb --username=$POSTGRES_USER --owner=$POSTGRES_USER bankdb

# Drop bankdb:
dropdb:
    docker compose exec db dropdb -U $POSTGRES_USER bankdb

# Apply migration to create tables
migrateup:
    migrate -path db/migrations -database "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/bankdb?sslmode=disable" up

# Apply migration to delete tables
migratedown:
    migrate -path db/migrations -database "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/bankdb?sslmode=disable" down    

# Generate code
sqlc:
    sqlc generate